# External mode: no infer container; store points to any OpenAI-compatible endpoint.
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: foxmemory-qdrant
    ports:
      - "6333:6333"
    volumes:
      - foxmemory_store_data:/qdrant/storage

  store:
    image: ${FOXMEMORY_STORE_IMAGE}
    container_name: foxmemory-store
    command: ["sh", "-lc", "cd /tmp && node /app/dist/index.js"]
    ports:
      - "8082:8082"
    environment:
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MEM0_LLM_MODEL=${MEM0_LLM_MODEL}
      - MEM0_EMBED_MODEL=${MEM0_EMBED_MODEL}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - MEM0_HISTORY_DB_PATH=/tmp/history.db
      - QDRANT_STORAGE_PATH=/qdrant/storage
    depends_on:
      - qdrant

volumes:
  foxmemory_store_data:
