# External mode: no infer container; store points to any OpenAI-compatible endpoint.
services:
  store:
    image: ${FOXMEMORY_STORE_IMAGE}
    container_name: foxmemory-store
    ports:
      - "8082:8082"
      - "6333:6333"
    environment:
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MEM0_LLM_MODEL=${MEM0_LLM_MODEL}
      - MEM0_EMBED_MODEL=${MEM0_EMBED_MODEL}
      - QDRANT_HOST=127.0.0.1
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - MEM0_HISTORY_DB_PATH=/tmp/history.db
      - QDRANT_STORAGE_PATH=/qdrant/storage
    volumes:
      - foxmemory_store_data:/qdrant/storage

volumes:
  foxmemory_store_data:
