services:
  infer:
    image: ${FOXMEMORY_INFER_IMAGE}
    container_name: foxmemory-infer
    ports:
      - "8081:8081"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OLLAMA_EMBED_MODEL=${OLLAMA_EMBED_MODEL}

  store:
    image: ${FOXMEMORY_STORE_IMAGE}
    container_name: foxmemory-store
    ports:
      - "8082:8082"
      - "6333:6333"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MEM0_LLM_MODEL=${MEM0_LLM_MODEL}
      - MEM0_EMBED_MODEL=${MEM0_EMBED_MODEL}
      - QDRANT_HOST=127.0.0.1
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - MEM0_HISTORY_DB_PATH=/tmp/history.db
      - QDRANT_STORAGE_PATH=/qdrant/storage
    volumes:
      - foxmemory_store_data:/qdrant/storage
    depends_on:
      - infer

volumes:
  foxmemory_store_data:
